[window]
opacity = {{custom.transparency}}
padding = { x = {{ custom.spacing_2 }}, y = {{ custom.spacing_2 }} }

[colors.primary]
background = "0x{{colors.surface.default.hex_stripped}}"
foreground = "0x{{colors.on_surface.default.hex_stripped}}"

[colors.normal]
black   = "0x{{colors.surface_container.default.hex_stripped}}"
white   = "0x{{colors.on_surface.default.hex_stripped}}"
blue    = "0x{{colors.primary.default.hex_stripped}}"
cyan    = "0x{{colors.primary_fixed.default.hex_stripped}}"
green   = "0x{{harmonized_colors.success.hex_stripped}}"
magenta = "0x{{colors.tertiary.default.hex_stripped}}"
red     = "0x{{colors.error.default.hex_stripped}}"
yellow  = "0x{{harmonized_colors.warning.hex_stripped}}"

[colors.bright]
black   = "0x{{colors.surface_container.default.hex_stripped}}"
white   = "0x{{colors.on_surface.default.hex_stripped}}"
blue    = "0x{{colors.primary.default.hex_stripped}}"
cyan    = "0x{{colors.primary_fixed.default.hex_stripped}}"
green   = "0x{{harmonized_colors.success.hex_stripped}}"
magenta = "0x{{colors.tertiary.default.hex_stripped}}"
red     = "0x{{colors.error.default.hex_stripped}}"
yellow  = "0x{{harmonized_colors.warning.hex_stripped}}"

[colors.cursor]
cursor = "0x{{colors.inverse_surface.default.hex_stripped}}"
text   = "0x{{colors.inverse_on_surface.default.hex_stripped}}"
